name: Update Algolia index

on:
  workflow_call:
  workflow_dispatch:
  schedule: 
    - cron: "0 3 * * *" # every day, 3am

env:
  MIX_ENV: dev
  USE_SERVER_SENT_EVENTS: "false"
  V3_URL: ${{ secrets.V3_URL }}
  V3_API_KEY: ${{ secrets.V3_API_KEY }}
  WARM_CACHES: "false"

jobs:
  algolia:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'mbta'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache/restore@v3
      with:
        path: ~/.asdf
        key: ci-asdf-cache-${{ hashFiles('.tool-versions') }}
        restore-keys: ci-asdf-cache-
    - uses: mbta/actions/reshim-asdf@v1
    - uses: actions/cache/restore@v3
      with:
        path: deps
        key: ci-mix-cache-${{ hashFiles('**/mix.lock') }}
        restore-keys: ci-mix-cache-
    - env:
        ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
        ALGOLIA_WRITE_KEY: ${{ secrets.ALGOLIA_WRITE_KEY }}
      run: mix algolia.update
