name: Dotcom Tests
on: 
  workflow_dispatch:
  pull_request_target:
    branches: '**'

env:
  MIX_ENV: test

jobs:

  # All other jobs in this workflow run after setup.
  # Setup installs/caches the languages from .tool-versions
  setup:
    name: Setup Dotcom dependencies and caches
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: <asdf> Restore cache of languages from .tool-versions
      uses: actions/cache@v2
      with:
        path: ~/.asdf
        key: ${{ runner.os }}-asdf-v2-${{ hashFiles('.tool-versions') }}
      id: asdf-cache
    - name: <asdf> Install languages from .tool-versions (if needed)
      uses: asdf-vm/actions/install@v1
      if: steps.asdf-cache.outputs.cache-hit != 'true'

  credo:
    name: Elixir linting w/ Credo
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
      - uses: actions/checkout@v2
      - name: <asdf> Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.asdf
          key: ${{ runner.os }}-asdf-v2-${{ hashFiles('.tool-versions') }}
      - name: <asdf> Set env vars
        run: |
          ASDF_DIR=$HOME/.asdf
          echo "ASDF_DIR=$ASDF_DIR" >> $GITHUB_ENV
          echo "ASDF_DATA_DIR=$ASDF_DIR" >> $GITHUB_ENV
          echo "$ASDF_DIR/bin" >> $GITHUB_PATH
          echo "$ASDF_DIR/shims" >> $GITHUB_PATH

      # Run credo, checking on the git diff between master and this commit, listing all issues
      # TODO: Show result in an annotation
      - run: mix credo diff master -a
