name: Publish docs

on:
  push:
    paths:
      - "**.ex"
      - "**.exs"
      - "**.md"
      - ".github/workflows/docs.yml"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.2
          elixir-version: 1.16.1
      - run: mix docs --formatter html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./doc
