name: Publish docs

on:
  push:
    paths:
      - "**.ex"
      - "**.exs"
      - "**.md"
      - ".github/workflows/docs.yml"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mix docs --formatter html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./doc
