name: Rebase dependabot branches onto master

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  get-prs:
    name: Get Dependabot PR list
    runs-on: ubuntu-latest
    outputs: 
      prs: ${{ steps.dependabot-pr-list.outputs.prs }}
    steps:
      - uses: actions/checkout@v2
      - id: dependabot-pr-list
        run: |
          PR_LIST=$(gh pr list | grep 'dependabot/' | cut -d$'\t'  -f 1 | tac | tr '\n' ' ')
          echo "::set-output name=prs::${PR_LIST}"
  
  rebase-prs:
    runs-on: ubuntu-latest
    needs: get-prs
    strategy:
      fail-fast: false
      matrix: 
        pr: ${{ fromJson(needs.get-prs.outputs.prs) }}
    continue-on-error: true
    steps:    
      - uses: actions/checkout@v2
      - run: echo ${{ matrix.pr }}  
      - name: Rebase PR#${{ matrix.pr }}
        env:
          PR: ${{ matrix.pr }}
        run: |
          gh pr checkout $PR
          git rebase master && EXIT_CODE=$? || EXIT_CODE=$?
          if [ "${EXIT_CODE}" == "0" ]
            git push --force
            gh pr ready $PR
          then
            git rebase --abort
          fi
